name: Run WebdriverIO tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            submodules: true

        - name: Install global dependencies
          run: sudo npm install yalc -g --force

        - name: Publish local packages
          run: yalc publish shared && yalc add @carved-rock-fitness/shared && yalc publish lib/create-react-app/packages/react-scripts && yalc add react-scripts

        - name: Install
          uses: ianwalter/puppeteer@master
          with:
            args: npm install

        # Wait for Netlify Deploy Preview to boot up
        - name: Wait for Netlify Deploy Preview Commit
          uses: kamranayub/wait-for-netlify-action@2.0.0
          id: netlify
          with:
            site_name: 'carved-rock-order-tracker-pwa'
            max_timeout: 180
          env:
            NETLIFY_TOKEN: ${{secrets.NETLIFY_TOKEN}}

        - name: Test
          uses: ianwalter/puppeteer@master
          env:
            WDIO_BASE_URL: ${{ steps.netlify.outputs.url }}
          with:
            args: npm run wdio

        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: wdio/logs